"""add password to members

Revision ID: 59e9fbd582f0
Revises: fc0f221709cf
Create Date: 2026-05-11 15:40:21.103910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e9fbd582f0'
down_revision: Union[str, Sequence[str], None] = 'fc0f221709cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('passsword', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'passsword')
    # ### end Alembic commands ###
