"""edit password attribute

Revision ID: c62a1f4cc649
Revises: 59e9fbd582f0
Create Date: 2026-05-12 06:37:43.024233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62a1f4cc649'
down_revision: Union[str, Sequence[str], None] = '59e9fbd582f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('members', 'passsword')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('passsword', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('members', 'password')
    # ### end Alembic commands ###
